Repository Akgop/SWEngineering-WebApp-Project-2021, pull requests merged in 2021-05, with the labels that each got.

#6 FE react.js 기본 개발 환경 구축 튜토리얼
  .gitignore
  client-side/package.json
  client-side/public/favicon.ico
  client-side/public/index.html
  client-side/public/logo192.png
  client-side/public/logo512.png
  client-side/public/manifest.json
  client-side/public/robots.txt
  client-side/src/App.css
  client-side/src/App.js
  client-side/src/App.test.js
  client-side/src/index.css
  client-side/src/index.js
  client-side/src/logo.svg
  client-side/src/reportWebVitals.js
  client-side/src/setupTests.js
  client-side/yarn.lock
Labels: reactjs

#11 react-router-dom 을 이용해서 페이지 이동
  client-side/package.json
  client-side/src/App.js
  client-side/src/Home/Home.js
  client-side/src/Landing/Landing.js
  client-side/src/MyPage/MyPage.js
  client-side/src/Navbar/About.js
  client-side/src/Navbar/CollapseNav.js
  client-side/src/Navbar/Navbar.js
  client-side/src/index.js
  client-side/yarn.lock
Labels: reactjs

#14 login using axios & redux
  client-side/package.json
  client-side/src/About/About.js
  client-side/src/App.js
  client-side/src/Components/CollapseNav.js
  client-side/src/Components/Footer.js
  client-side/src/Components/Navbar.js
  client-side/src/Home/Home.js
  client-side/src/Landing/Landing.js
  client-side/src/Login/Login.js
  client-side/src/MyPage/MyPage.js
  client-side/src/_actions/types.js
  client-side/src/_actions/user_action.js
  client-side/src/_reducers/index.js
  client-side/src/_reducers/user_reducer.js
  client-side/src/index.js
  client-side/yarn.lock
Labels: reactjs

#13 server-side 환경 구축
  package-lock.json
  server-side/app.js
  server-side/bin/www
  server-side/package-lock.json
  server-side/package.json
  server-side/routes/index.js
  server-side/test.rest
  server-side/views/error.jade
  server-side/views/index.jade
  server-side/views/layout.jade
Labels: nodejs

#19 react & node interaction, added CORS middle ware
  server-side/app.js
  server-side/package-lock.json
  server-side/package.json
  server-side/routes/login.js
Labels: nodejs

#23 POST방식 로그인/회원가입 백엔드 구현
  package-lock.json
  server-side/package-lock.json
  server-side/package.json
  server-side/routes/dbConfig.js
  server-side/routes/index.js
  server-side/routes/login.js
  server-side/routes/register.js
  server-side/test.rest
Labels: mysql, nodejs

#30 서버측 로그인/회원가입 구현
  server-side/routes/login.js
  server-side/routes/register.js
  server-side/test.rest
Labels: mysql, nodejs

#29 메인페이지 구성
  server-side/public/assets/img/budaejjigae.jpg
  server-side/public/assets/img/misosoup.jpg
  server-side/routes/index.js
  server-side/routes/order.js
  server-side/views/index.ejs
  server-side/views/login.ejs
  server-side/views/main.ejs
  server-side/views/register.ejs
Labels: nodejs

#34 [Server] mypage 기본기능 구현
  .gitignore
  server-side/app.js
  server-side/package.json
  server-side/routes/index.js
  server-side/routes/login.js
  server-side/routes/mypage.js
  server-side/test.rest
Labels: nodejs

#40 [Server] 회원 관리 (관리자) 구현
  server-side/app.js
  server-side/routes/login.js
  server-side/routes/management.js
  server-side/routes/mypage.js
  server-side/routes/register.js
Labels: nodejs

#41 [Server] 장바구니 기능 구현 수정본
  server-side/app.js
  server-side/routes/basket.js
Labels: mysql, nodejs

#42 [Server]상품 세부사항 조회 기능 구현
  server-side/app.js
  server-side/routes/product_detail.js
Labels: mysql, nodejs

#44 유저 포인트 추가 코드 작성
  server-side/package-lock.json
  server-side/package.json
  server-side/routes/index.js
  server-side/routes/login.js
  server-side/routes/mypage.js
  server-side/views/admin_main.ejs
  server-side/views/mypage.ejs
Labels: mysql, nodejs

#47 [client] 장바구니에서 전체 주문하는 코드
  server-side/app.js
  server-side/routes/order.js
  server-side/views/basket.ejs
  server-side/views/product_detail.ejs
Labels: nodejs

#49 [Server] 주문하기 기능 구현(수정필요)
  server-side/routes/order.js
Labels: mysql, nodejs

#50 [Server] 판매자 상품등록 기능구현
  server-side/routes/product_register.js
Labels: mysql, nodejs

#52 [Server] 오더 기능 마무리
  server-side/routes/index.js
  server-side/routes/order.js
  server-side/views/basket.ejs
  server-side/views/company_main.ejs
  server-side/views/mypage.ejs
  server-side/views/product_detail.ejs
Labels: mysql, nodejs
