Repository Akgop/SWEngineering-WebApp-Project-2021, pull requests merged in 2021-06, with the labels that each got.

#54 판매자 물품 등록 구현
  server-side/app.js
  server-side/package-lock.json
  server-side/package.json
  server-side/public/assets/img/img_1.jpg
  server-side/public/assets/img/img_1_big.jpg
  server-side/public/assets/img/img_2.jpg
  server-side/public/assets/img/img_3.jpg
  server-side/public/assets/img/img_4.jpg
  server-side/public/assets/img/img_5.jpg
  server-side/public/assets/img/img_6.jpg
  server-side/public/assets/img/logo-adobe.png
  server-side/public/assets/img/logo-apple.png
  server-side/public/assets/img/logo-google.png
  server-side/public/assets/img/logo-netflix.png
  server-side/public/assets/img/logo-nike.png
  server-side/public/assets/img/logo-uber.png
  server-side/public/assets/img/person_1.jpg
  server-side/public/assets/img/person_1_sq.jpg
  server-side/public/assets/img/person_2.jpg
  server-side/public/assets/img/person_3.jpg
  server-side/routes/login.js
  server-side/routes/product.js
  server-side/routes/product_register.js
  server-side/views/company_main.ejs
  server-side/views/product_register.ejs
Labels: nodejs

#56 [client, server] 판매자 상품 추가, 수정, 삭제 기능 모두 구현
  server-side/public/assets/img/ham.jpg
  server-side/routes/index.js
  server-side/routes/product.js
  server-side/views/company_main.ejs
Labels: nodejs

#55 [Server] 리뷰 기능 구현 및 상품 리뷰점수 업데이트 기능 구현
  server-side/app.js
  server-side/routes/order_static.js
  server-side/routes/product_delete.js
  server-side/routes/review.js
Labels: mysql, nodejs

#57 Review update
  server-side/app.js
  server-side/routes/review.js
Labels: mysql, nodejs

#59 [client] 매출 통계 시각화 by chart.js
  server-side/routes/order.js
  server-side/routes/product.js
  server-side/views/company_main.ejs
  server-side/views/order_statistic.ejs
  server-side/views/product_register.ejs
Labels: nodejs

#60 [Server] 판매내역 조회기능 구현
  server-side/routes/companysalelist.js
Labels: mysql, nodejs

#62 재료 sql오류 수정, 개별 주문 버튼 활성화
  server-side/public/assets/img/김치.jpg
  server-side/routes/product.js
  server-side/views/product_detail.ejs
Labels: bug, mysql, nodejs

#63 changed admin-main
  server-side/views/admin_main.ejs
Labels: bug, nodejs

#64 debugging
  server-side/routes/companysalelist.js
  server-side/views/index.ejs
  server-side/views/ingredient.ejs
  server-side/views/mypage.ejs
  server-side/views/product.ejs
Labels: bug

#66 회원가입 오류 수정
  server-side/routes/register.js
Labels: bug
